apiVersion: v1
kind: Service
metadata:
    name: ui
    namespace: billmanagement
    labels:
        app: ui
spec:
    selector:
        app: ui
    type: NodePort
    ports:
        - name: http
          port: 80
          targetPort: 80
          nodePort: 30200
